document.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>");
document.write("<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\" xmlns:b=\"http:\/\/www.google.com\/2005\/gml\/b\" xmlns:data=\"http:\/\/www.google.com\/2005\/gml\/data\" xmlns:expr=\"http:\/\/www.google.com\/2005\/gml\/expr\">");
document.write("<head>");
document.write("<style>");
document.write(".wrap { ");
document.write("   white-space: pre-wrap;      \/* CSS3 *\/   ");
document.write("   white-space: -moz-pre-wrap; \/* Firefox *\/    ");
document.write("   white-space: -pre-wrap;     \/* Opera <7 *\/   ");
document.write("   white-space: -o-pre-wrap;   \/* Opera 7 *\/    ");
document.write("   word-wrap: break-word;      \/* IE *\/");
document.write("}");
document.write("<\/style>");
document.write("<\/head>");
document.write("<body>");
document.write("<div>");
document.write("    <div style=\"width: 180px;border: 1px solid black; display: inline-block;\" align=\"center\"><div>Item 1<\/div><button onclick=\"getInvoice('1000', 'User_Picked_1000');\" id=\"request1000\" style=\"maxwidth:150px;margin-bottom:10px;margin-top:20px;\">1000 sats<\/button><\/div>");
document.write("  <div style=\"width: 180px;border: 1px solid black; display: inline-block;\" align=\"center\"><div>Item 2<\/div><button onclick=\"getInvoice('1500', 'User_Picked_1500');\" id=\"request1500\" style=\"max-width:150px;margin-bottom:10px;margin-top:20px;\">1500 sats<\/button><\/div>");
document.write("  <div style=\"width: 180px;border: 1px solid black; display: inline-block;\" align=\"center\"><div>Item 3<\/div><button onclick=\"getInvoice('2000', 'User_Picked_2000');\" id=\"request1500\" style=\"max-width:150px;margin-bottom:10px;margin-top:20px;\">2000 sats<\/button><\/div>");
document.write("  <div style=\"border: 1px solid black; max-width: 180px; display: inline-block;float:left;margin-right:4px;\" align=\"center\">");
document.write("    <span style=\"line-height:45px;font-weight:bold;\">Donation Box<\/span>");
document.write("    <input id=\"donateamount\" style=\"width:80%; margin:2px; color: #aaa;\" type=\"text\" name=\"amount\" value=\"100000\" onfocus=\"if (this.value == '100000') {changeAmount();}\" onblur=\"if (this.value == '') {changeAmountBack();}\" onkeypress=\"return event.charCode >= 48 && event.charCode <= 57\"><br \/>");
document.write("    <input id=\"donatememo\" style=\"width:80%; margin:2px; color: #aaa;\" type=\"text\" name=\"memo\" value=\"Personalized_message\" onfocus=\"if (this.value == 'Personalized_message') {changeMemo();}\" onblur=\"if (this.value == '') {changeMemoBack();}\" onkeypress=\"return event.charCode != 32 && event.charCode != 186 && event.charCode != 37 && event.charCode != 39\" maxlength=\"25\"><br \/>");
document.write("    <button id=\"donate\" style=\"margin: 10px;\" onclick=\"getInvoice(document.getElementById('donateamount').value, document.getElementById('donatememo').value);\">Donate<\/button>");
document.write("  <\/div>");
document.write("<\/div>");
document.write("<br \/><br \/>");
document.write("<div id=\"invoiceBox\" class=\"wrap\" style=\"display: none; border: 1px solid #e8e8e8; max-width: 300px; overflow: hidden;padding:20px;\" align=\"center\"><strong>Please pay this invoice<\/strong><br \/><br \/><img width=\"200px\" height=\"200px\" id=\"invoiceQR\" src=\"http:\/\/qrickit.com\/api\/qr.php?qrsize=200&d=[[insert-text-here]]\" \/><div id=\"invoiceInnerBox\"><\/div><\/div>");
document.write("");
document.write("<script type='text\/javascript'>");
document.write("    ");
document.write("function changeAmount() {");
document.write("document.getElementById(\"donateamount\").value = '';");
document.write("document.getElementById(\"donateamount\").style.color = '#000';");
document.write("}");
document.write("");
document.write("function changeAmountBack() {");
document.write("document.getElementById(\"donateamount\").value = '100000';");
document.write("document.getElementById(\"donateamount\").style.color = '#aaa';");
document.write("}");
document.write("    ");
document.write("function changeMemo() {");
document.write("document.getElementById(\"donatememo\").value = '';");
document.write("document.getElementById(\"donatememo\").style.color = '#000';");
document.write("}");
document.write("");
document.write("function changeMemoBack() {");
document.write("document.getElementById(\"donatememo\").value = 'Personalized_message';");
document.write("document.getElementById(\"donatememo\").style.color = '#aaa';");
document.write("}    ");
document.write("");
document.write("function getInvoice(amount, memo) {");
document.write("  ");
document.write("  \"use strict\";");
document.write("");
document.write("  var btn1000 = document.getElementById(\"request1000\");");
document.write("  var invoiceBox = document.getElementById(\"invoiceBox\");");
document.write("  var invoiceInnerBox = document.getElementById(\"invoiceInnerBox\");");
document.write("  var invoiceQR = document.getElementById(\"invoiceQR\");");
document.write("  ");
document.write("  var request = new XMLHttpRequest();");
document.write("  ");
document.write("  \/\/ keep track of the request");
document.write("  request.onreadystatechange = function() {");
document.write("    \/\/ check if the response data send back to us ");
document.write("    if(request.readyState === 4) {");
document.write("      \/\/ make invoiceBox visible");
document.write("      invoiceBox.style.display = \"block\";");
document.write("      \/\/ uncomment the line below to see the request");
document.write("      \/\/ console.log(request);");
document.write("      \/\/ check if the request is successful");
document.write("      if(request.status === 200) {");
document.write("        \/\/ insert invoice");
document.write("        invoiceInnerBox.innerHTML = request.responseText;");
document.write("        invoiceQR.src = \"http:\/\/qrickit.com\/api\/qr.php?qrsize=200&d=\" + request.responseText;");
document.write("      } else {");
document.write("        invoiceBox.innerHTML = \"An error occurred during your request: \" +  request.status + \" \" + request.statusText;");
document.write("      }");
document.write("    }");
document.write("  }");
document.write("");
document.write("  \/\/ specify the type of request");
document.write("  request.open(\"GET\", \"http:\/\/73.18.38.217:3200\/test5.php?amt=\" + amount + \"&memo=\" + memo + \"\", true);");
document.write("  \/\/ send the request");
document.write("  request.send();");
document.write("  ");
document.write("}");
document.write("<\/script>    ");
document.write("");
document.write("<\/body>");
document.write("<\/html>");
